export const countries = [
    {
      ID: 65,
      nomFr: 'France',
      nationaliteFr: 'Française',
      nomEn: 'France',
      nationaliteEn: 'French',
      alpha2Code: 'FR',
      alpha3Code: 'FRA',
      dialCode: '33',
      prep: 'en',
      phoneFormat: '9-99-99-99-99',
    },
    {
      ID: 1,
      nomFr: 'Afghanistan',
      nationaliteFr: 'Afghan',
      nomEn: 'Afghanistan',
      nationaliteEn: 'Afghan',
      alpha2Code: 'AF',
      alpha3Code: 'AFG',
      dialCode: '93',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 2,
      nomFr: 'Afrique du Sud',
      nationaliteFr: 'Sud-Africain',
      nomEn: 'South Africa',
      nationaliteEn: 'South African',
      alpha2Code: 'ZA',
      alpha3Code: 'ZAF',
      dialCode: '27',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 3,
      nomFr: 'Albanie',
      nationaliteFr: 'Albanais',
      nomEn: 'Albania',
      nationaliteEn: 'Albanian',
      alpha2Code: 'AL',
      alpha3Code: 'ALB',
      dialCode: '355',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 4,
      nomFr: 'Algérie',
      nationaliteFr: 'Algérien',
      nomEn: 'Algeria',
      nationaliteEn: 'Algerian',
      alpha2Code: 'DZ',
      alpha3Code: 'DZA',
      dialCode: '213',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 5,
      nomFr: 'Allemagne',
      nationaliteFr: 'Allemand',
      nomEn: 'Germany',
      nationaliteEn: 'German',
      alpha2Code: 'DE',
      alpha3Code: 'DEU',
      dialCode: '49',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 6,
      nomFr: 'Andorre',
      nationaliteFr: 'Andorran',
      nomEn: 'Andorra',
      nationaliteEn: 'Andorran',
      alpha2Code: 'AD',
      alpha3Code: 'AND',
      dialCode: '376',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 7,
      nomFr: 'Angola',
      nationaliteFr: 'Angolais',
      nomEn: 'Angola',
      nationaliteEn: 'Angolan',
      alpha2Code: 'AO',
      alpha3Code: 'AGO',
      dialCode: '244',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 8,
      nomFr: 'Antigua-et-Barbuda',
      nationaliteFr: 'Antiguayen',
      nomEn: 'Antigua and Barbuda',
      nationaliteEn: 'Antiguan',
      alpha2Code: 'AG',
      alpha3Code: 'ATG',
      dialCode: '1268',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 9,
      nomFr: 'Arabie Saoudite',
      nationaliteFr: 'Saoudien',
      nomEn: 'Saudi Arabia',
      nationaliteEn: 'Saudi',
      alpha2Code: 'SA',
      alpha3Code: 'SAU',
      dialCode: '966',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 10,
      nomFr: 'Argentine',
      nationaliteFr: 'Argentin',
      nomEn: 'Argentina',
      nationaliteEn: 'Argentine',
      alpha2Code: 'AR',
      alpha3Code: 'ARG',
      dialCode: '54',
      prep: 'en',
      phoneFormat: '99-9999-9999',
    },
    {
      ID: 11,
      nomFr: 'Arménie',
      nationaliteFr: 'Arménien',
      nomEn: 'Armenia',
      nationaliteEn: 'Armenian',
      alpha2Code: 'AM',
      alpha3Code: 'ARM',
      dialCode: '374',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 12,
      nomFr: 'Australie',
      nationaliteFr: 'Australien',
      nomEn: 'Australia',
      nationaliteEn: 'Australian',
      alpha2Code: 'AU',
      alpha3Code: 'AUS',
      dialCode: '61',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 13,
      nomFr: 'Autriche',
      nationaliteFr: 'Autrichien',
      nomEn: 'Austria',
      nationaliteEn: 'Austrian',
      alpha2Code: 'AT',
      alpha3Code: 'AUT',
      dialCode: '43',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 14,
      nomFr: 'Azerbaïdjan',
      nationaliteFr: 'Azéri',
      nomEn: 'Azerbaijan',
      nationaliteEn: 'Azerbaijani',
      alpha2Code: 'AZ',
      alpha3Code: 'AZE',
      dialCode: '994',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 15,
      nomFr: 'Bahamas',
      nationaliteFr: 'Bahamien',
      nomEn: 'Bahamas',
      nationaliteEn: 'Bahamian',
      alpha2Code: 'BS',
      alpha3Code: 'BHS',
      dialCode: '1242',
      prep: 'en',
      phoneFormat: '999-9999',
    },
    {
      ID: 16,
      nomFr: 'Bahreïn',
      nationaliteFr: 'Bahreïnien',
      nomEn: 'Bahrain',
      nationaliteEn: 'Bahraini',
      alpha2Code: 'BH',
      alpha3Code: 'BHR',
      dialCode: '973',
      prep: 'à',
      phoneFormat: '9999-9999',
    },
    {
      ID: 17,
      nomFr: 'Bangladesh',
      nationaliteFr: 'Bangladais',
      nomEn: 'Bangladesh',
      nationaliteEn: 'Bangladeshi',
      alpha2Code: 'BD',
      alpha3Code: 'BGD',
      dialCode: '880',
      prep: 'au',
      phoneFormat: '99-9999-9999',
    },
    {
      ID: 18,
      nomFr: 'Barbade',
      nationaliteFr: 'Barbadien',
      nomEn: 'Barbados',
      nationaliteEn: 'Barbadian',
      alpha2Code: 'BB',
      alpha3Code: 'BRB',
      dialCode: '1246',
      prep: 'à',
      phoneFormat: '999-9999',
    },
    {
      ID: 19,
      nomFr: 'Belau / Palau / Palaos',
      nationaliteFr: 'Paluan',
      nomEn: 'Palau',
      nationaliteEn: 'Palauan',
      alpha2Code: 'PW',
      alpha3Code: 'PLW',
      dialCode: '680',
      prep: 'aux',
      phoneFormat: '999-9999',
    },
    {
      ID: 20,
      nomFr: 'Belgique',
      nationaliteFr: 'Belge',
      nomEn: 'Belgium',
      nationaliteEn: 'Belgian',
      alpha2Code: 'BE',
      alpha3Code: 'BEL',
      dialCode: '32',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 21,
      nomFr: 'Belize',
      nationaliteFr: 'Belizien',
      nomEn: 'Belize',
      nationaliteEn: 'Belizean',
      alpha2Code: 'BZ',
      alpha3Code: 'BLZ',
      dialCode: '501',
      prep: 'au',
      phoneFormat: '999-9999',
    },
    {
      ID: 22,
      nomFr: 'Bénin',
      nationaliteFr: 'Béninois',
      nomEn: 'Benin',
      nationaliteEn: 'Beninese',
      alpha2Code: 'BJ',
      alpha3Code: 'BEN',
      dialCode: '229',
      prep: 'au',
      phoneFormat: '99-999-999',
    },
    {
      ID: 23,
      nomFr: 'Bhoutan',
      nationaliteFr: 'Bhoutanais',
      nomEn: 'Bhutan',
      nationaliteEn: 'Bhutanese',
      alpha2Code: 'BT',
      alpha3Code: 'BTN',
      dialCode: '975',
      prep: 'au',
      phoneFormat: '99-99-99-99',
    },
    {
      ID: 24,
      nomFr: 'Biélorussie',
      nationaliteFr: 'Biélorusse',
      nomEn: 'Belarus',
      nationaliteEn: 'Belarusian',
      alpha2Code: 'BY',
      alpha3Code: 'BLR',
      dialCode: '375',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 25,
      nomFr: 'Birmanie',
      nationaliteFr: 'Birman',
      nomEn: 'Myanmar',
      nationaliteEn: 'Burmese',
      alpha2Code: 'MM',
      alpha3Code: 'MMR',
      dialCode: '95',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 26,
      nomFr: 'Bolivie',
      nationaliteFr: 'Bolivien',
      nomEn: 'Bolivia',
      nationaliteEn: 'Bolivian',
      alpha2Code: 'BO',
      alpha3Code: 'BOL',
      dialCode: '591',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 27,
      nomFr: 'Bosnie-Herzégovine',
      nationaliteFr: 'Bosniaque',
      nomEn: 'Bosnia and Herzegovina',
      nationaliteEn: 'Bosnian',
      alpha2Code: 'BA',
      alpha3Code: 'BIH',
      dialCode: '387',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 28,
      nomFr: 'Botswana',
      nationaliteFr: 'Botswanais',
      nomEn: 'Botswana',
      nationaliteEn: 'Botswanan',
      alpha2Code: 'BW',
      alpha3Code: 'BWA',
      dialCode: '267',
      prep: 'au',
      phoneFormat: '99999999',
    },
    {
      ID: 29,
      nomFr: 'Brésil',
      nationaliteFr: 'Brésilien',
      nomEn: 'Brazil',
      nationaliteEn: 'Brazilian',
      alpha2Code: 'BR',
      alpha3Code: 'BRA',
      dialCode: '55',
      prep: 'au',
      phoneFormat: '99-99-99-99',
    },
    {
      ID: 30,
      nomFr: 'Brunei',
      nationaliteFr: 'Brunéien',
      nomEn: 'Brunei',
      nationaliteEn: 'Bruneian',
      alpha2Code: 'BN',
      alpha3Code: 'BRN',
      dialCode: '673',
      prep: 'au',
      phoneFormat: '999-9999',
    },
    {
      ID: 31,
      nomFr: 'Bulgarie',
      nationaliteFr: 'Bulgare',
      nomEn: 'Bulgaria',
      nationaliteEn: 'Bulgarian',
      alpha2Code: 'BG',
      alpha3Code: 'BGR',
      dialCode: '359',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 32,
      nomFr: 'Burkina Faso',
      nationaliteFr: 'Burkinabé',
      nomEn: 'Burkina Faso',
      nationaliteEn: 'Burkinese',
      alpha2Code: 'BF',
      alpha3Code: 'BFA',
      dialCode: '226',
      prep: 'au',
      phoneFormat: '99-999-999',
    },
    {
      ID: 33,
      nomFr: 'Burundi',
      nationaliteFr: 'Burundais',
      nomEn: 'Burundi',
      nationaliteEn: 'Burundian',
      alpha2Code: 'BI',
      alpha3Code: 'BDI',
      dialCode: '257',
      prep: 'au',
      phoneFormat: '99-99-99-99',
    },
    {
      ID: 34,
      nomFr: 'Cambodge',
      nationaliteFr: 'Cambodgien',
      nomEn: 'Cambodia',
      nationaliteEn: 'Cambodian',
      alpha2Code: 'KH',
      alpha3Code: 'KHM',
      dialCode: '855',
      prep: 'au',
      phoneFormat: '99-99-99-99',
    },
    {
      ID: 35,
      nomFr: 'Cameroun',
      nationaliteFr: 'Camerounais',
      nomEn: 'Cameroon',
      nationaliteEn: 'Cameroonian',
      alpha2Code: 'CM',
      alpha3Code: 'CMR',
      dialCode: '237',
      prep: 'au',
      phoneFormat: '99-999-999',
    },
    {
      ID: 36,
      nomFr: 'Canada',
      nationaliteFr: 'Canadien',
      nomEn: 'Canada',
      nationaliteEn: 'Canadian',
      alpha2Code: 'CA',
      alpha3Code: 'CAN',
      dialCode: '1',
      prep: 'au',
      phoneFormat: '999-9999',
    },
    {
      ID: 37,
      nomFr: 'Cap-Vert',
      nationaliteFr: 'Capverdien',
      nomEn: 'Cape Verde',
      nationaliteEn: 'Cape Verdean',
      alpha2Code: 'CV',
      alpha3Code: 'CPV',
      dialCode: '238',
      prep: 'au',
      phoneFormat: '99-999-999',
    },
    {
      ID: 38,
      nomFr: 'Centrafrique',
      nationaliteFr: 'Centrafricain',
      nomEn: 'Central African Republic',
      nationaliteEn: 'Central African',
      alpha2Code: 'CF',
      alpha3Code: 'CAF',
      dialCode: '236',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 39,
      nomFr: 'Chili',
      nationaliteFr: 'Chilien',
      nomEn: 'Chile',
      nationaliteEn: 'Chilean',
      alpha2Code: 'CL',
      alpha3Code: 'CHL',
      dialCode: '56',
      prep: 'au',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 40,
      nomFr: 'Chine',
      nationaliteFr: 'Chinois',
      nomEn: 'China',
      nationaliteEn: 'Chinese',
      alpha2Code: 'CN',
      alpha3Code: 'CHN',
      dialCode: '86',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 41,
      nomFr: 'Chypre',
      nationaliteFr: 'Chypriote',
      nomEn: 'Cyprus',
      nationaliteEn: 'Cypriot',
      alpha2Code: 'CY',
      alpha3Code: 'CYP',
      dialCode: '357',
      prep: 'à',
      phoneFormat: '99-999-999',
    },
    {
      ID: 42,
      nomFr: 'Colombie',
      nationaliteFr: 'Colombien',
      nomEn: 'Colombia',
      nationaliteEn: 'Colombian',
      alpha2Code: 'CO',
      alpha3Code: 'COL',
      dialCode: '57',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 43,
      nomFr: 'Comores',
      nationaliteFr: 'Comorien',
      nomEn: 'Comoros',
      nationaliteEn: 'Comorian',
      alpha2Code: 'KM',
      alpha3Code: 'COM',
      dialCode: '269',
      prep: 'aux',
      phoneFormat: '99-999-999',
    },
    {
      ID: 44,
      nomFr: 'Congo-Brazzaville',
      nationaliteFr: 'Congolais',
      nomEn: 'Republic of the Congo',
      nationaliteEn: 'Congolese',
      alpha2Code: 'CG',
      alpha3Code: 'COG',
      dialCode: '242',
      prep: 'au',
      phoneFormat: '99-99-99999',
    },
    {
      ID: 45,
      nomFr: 'Congo-Kinshasa ou RDC',
      nationaliteFr: 'Congolais',
      nomEn: 'Democratic Republic of the Congo',
      nationaliteEn: 'Congolese',
      alpha2Code: 'CD',
      alpha3Code: 'COD',
      dialCode: '243',
      prep: 'au',
      phoneFormat: '9-999-99-99',
    },
    {
      ID: 46,
      nomFr: 'Corée du Nord',
      nationaliteFr: 'Nord-Coréen',
      nomEn: 'North Korea',
      nationaliteEn: 'North Korean',
      alpha2Code: 'KP',
      alpha3Code: 'PRK',
      dialCode: '850',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 47,
      nomFr: 'Corée du Sud',
      nationaliteFr: 'Sud-Coréen',
      nomEn: 'South Korea',
      nationaliteEn: 'South Korean',
      alpha2Code: 'KR',
      alpha3Code: 'KOR',
      dialCode: '82',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 48,
      nomFr: 'Costa Rica',
      nationaliteFr: 'Costaricain',
      nomEn: 'Costa Rica',
      nationaliteEn: 'Costa Rican',
      alpha2Code: 'CR',
      alpha3Code: 'CRI',
      dialCode: '506',
      prep: 'au',
      phoneFormat: '9999-9999',
    },
    {
      ID: 49,
      nomFr: "Côte d'Ivoire",
      nationaliteFr: 'Ivoirien',
      nomEn: 'Ivory Coast',
      nationaliteEn: 'Ivorian',
      alpha2Code: 'CI',
      alpha3Code: 'CIV',
      dialCode: '225',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 50,
      nomFr: 'Croatie',
      nationaliteFr: 'Croate',
      nomEn: 'Croatia',
      nationaliteEn: 'Croatian',
      alpha2Code: 'HR',
      alpha3Code: 'HRV',
      dialCode: '385',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 51,
      nomFr: 'Cuba',
      nationaliteFr: 'Cubain',
      nomEn: 'Cuba',
      nationaliteEn: 'Cuban',
      alpha2Code: 'CU',
      alpha3Code: 'CUB',
      dialCode: '53',
      prep: 'à',
      phoneFormat: '99-99-99-99',
    },
    {
      ID: 52,
      nomFr: 'Danemark',
      nationaliteFr: 'Danois',
      nomEn: 'Denmark',
      nationaliteEn: 'Danish',
      alpha2Code: 'DK',
      alpha3Code: 'DNK',
      dialCode: '45',
      prep: 'au',
      phoneFormat: '99-99-99-99',
    },
    {
      ID: 53,
      nomFr: 'Djibouti',
      nationaliteFr: 'Djiboutien',
      nomEn: 'Djibouti',
      nationaliteEn: 'Djiboutian',
      alpha2Code: 'DJ',
      alpha3Code: 'DJI',
      dialCode: '253',
      prep: 'à',
      phoneFormat: '99-99-99-99',
    },
    {
      ID: 54,
      nomFr: 'Dominique',
      nationaliteFr: 'Dominicain',
      nomEn: 'Dominica',
      nationaliteEn: 'Dominican',
      alpha2Code: 'DM',
      alpha3Code: 'DMA',
      dialCode: '1767',
      prep: 'à la',
      phoneFormat: '999-9999',
    },
    {
      ID: 55,
      nomFr: 'Égypte',
      nationaliteFr: 'Égyptien',
      nomEn: 'Egypt',
      nationaliteEn: 'Egyptian',
      alpha2Code: 'EG',
      alpha3Code: 'EGY',
      dialCode: '20',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 56,
      nomFr: 'Émirats arabes unis',
      nationaliteFr: 'Émirienne',
      nomEn: 'United Arab Emirates',
      nationaliteEn: 'Emirati',
      alpha2Code: 'AE',
      alpha3Code: 'ARE',
      dialCode: '971',
      prep: 'aux',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 57,
      nomFr: 'Équateur',
      nationaliteFr: 'Équatorienne',
      nomEn: 'Ecuador',
      nationaliteEn: 'Ecuadorian',
      alpha2Code: 'EC',
      alpha3Code: 'ECU',
      dialCode: '593',
      prep: 'en',
      phoneFormat: '9-999-999',
    },
    {
      ID: 58,
      nomFr: 'Érythrée',
      nationaliteFr: 'Érythréenne',
      nomEn: 'Eritrea',
      nationaliteEn: 'Eritrean',
      alpha2Code: 'ER',
      alpha3Code: 'ERI',
      dialCode: '291',
      prep: 'en',
      phoneFormat: '9-999-999',
    },
    {
      ID: 59,
      nomFr: 'Espagne',
      nationaliteFr: 'Espagnole',
      nomEn: 'Spain',
      nationaliteEn: 'Spanish',
      alpha2Code: 'ES',
      alpha3Code: 'ESP',
      dialCode: '34',
      prep: 'en',
      phoneFormat: '999-99-99-99',
    },
    {
      ID: 60,
      nomFr: 'Estonie',
      nationaliteFr: 'Estonienne',
      nomEn: 'Estonia',
      nationaliteEn: 'Estonian',
      alpha2Code: 'EE',
      alpha3Code: 'EST',
      dialCode: '372',
      prep: 'en',
      phoneFormat: '9999-9999',
    },
    {
      ID: 61,
      nomFr: 'États-Unis',
      nationaliteFr: 'Américaine',
      nomEn: 'United States',
      nationaliteEn: 'American',
      alpha2Code: 'US',
      alpha3Code: 'USA',
      dialCode: '1',
      prep: 'aux',
      phoneFormat: '999-9999',
    },
    {
      ID: 62,
      nomFr: 'Éthiopie',
      nationaliteFr: 'Éthiopienne',
      nomEn: 'Ethiopia',
      nationaliteEn: 'Ethiopian',
      alpha2Code: 'ET',
      alpha3Code: 'ETH',
      dialCode: '251',
      prep: 'en',
      phoneFormat: '999-99-9999',
    },
    {
      ID: 63,
      nomFr: 'Fidji (îles)',
      nationaliteFr: 'Fidjienne',
      nomEn: 'Fiji',
      nationaliteEn: 'Fijian',
      alpha2Code: 'FJ',
      alpha3Code: 'FJI',
      dialCode: '679',
      prep: 'aux',
      phoneFormat: '999-9999',
    },
    {
      ID: 64,
      nomFr: 'Finlande',
      nationaliteFr: 'Finlandaise',
      nomEn: 'Finland',
      nationaliteEn: 'Finnish',
      alpha2Code: 'FI',
      alpha3Code: 'FIN',
      dialCode: '358',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
  
    {
      ID: 66,
      nomFr: 'Gabon',
      nationaliteFr: 'Gabonaise',
      nomEn: 'Gabon',
      nationaliteEn: 'Gabonese',
      alpha2Code: 'GA',
      alpha3Code: 'GAB',
      dialCode: '241',
      prep: 'au',
      phoneFormat: '99-99-99-99',
    },
    {
      ID: 67,
      nomFr: 'Gambie',
      nationaliteFr: 'Gambienne',
      nomEn: 'Gambia',
      nationaliteEn: 'Gambian',
      alpha2Code: 'GM',
      alpha3Code: 'GMB',
      dialCode: '220',
      prep: 'en',
      phoneFormat: '999-9999',
    },
    {
      ID: 68,
      nomFr: 'Géorgie',
      nationaliteFr: 'Géorgienne',
      nomEn: 'Georgia',
      nationaliteEn: 'Georgian',
      alpha2Code: 'GE',
      alpha3Code: 'GEO',
      dialCode: '995',
      prep: 'en',
      phoneFormat: '999-999-999',
    },
    {
      ID: 69,
      nomFr: 'Ghana',
      nationaliteFr: 'Ghanéenne',
      nomEn: 'Ghana',
      nationaliteEn: 'Ghanaian',
      alpha2Code: 'GH',
      alpha3Code: 'GHA',
      dialCode: '233',
      prep: 'au',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 70,
      nomFr: 'Grèce',
      nationaliteFr: 'Grec(que)',
      nomEn: 'Greece',
      nationaliteEn: 'Greek',
      alpha2Code: 'GR',
      alpha3Code: 'GRC',
      dialCode: '30',
      prep: 'en',
      phoneFormat: '999-9999',
    },
    {
      ID: 71,
      nomFr: 'Grenade',
      nationaliteFr: 'Grenadienne',
      nomEn: 'Grenada',
      nationaliteEn: 'Grenadian',
      alpha2Code: 'GD',
      alpha3Code: 'GRD',
      dialCode: '1473',
      prep: 'à',
      phoneFormat: '999-9999',
    },
    {
      ID: 72,
      nomFr: 'Guatemala',
      nationaliteFr: 'Guatémaltèque',
      nomEn: 'Guatemala',
      nationaliteEn: 'Guatemalan',
      alpha2Code: 'GT',
      alpha3Code: 'GTM',
      dialCode: '502',
      prep: 'au',
      phoneFormat: '9999-9999',
    },
    {
      ID: 73,
      nomFr: 'Guinée-Bissau',
      nationaliteFr: 'Bissau-Guinéenne',
      nomEn: 'Guinea-Bissau',
      nationaliteEn: 'Bissau-Guinean',
      alpha2Code: 'GW',
      alpha3Code: 'GNB',
      dialCode: '245',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 74,
      nomFr: 'Guinée-Conakry',
      nationaliteFr: 'Guinéenne',
      nomEn: 'Guinea-Conakry',
      nationaliteEn: 'Guinean',
      alpha2Code: 'GN',
      alpha3Code: 'GIN',
      dialCode: '224',
      prep: 'en',
      phoneFormat: '999-999-999',
    },
    {
      ID: 75,
      nomFr: 'Guinée équatoriale',
      nationaliteFr: 'Équato-Guinéenne',
      nomEn: 'Equatorial Guinea',
      nationaliteEn: 'Equatoguinean',
      alpha2Code: 'GQ',
      alpha3Code: 'GNQ',
      dialCode: '240',
      prep: 'en',
      phoneFormat: '999-999-999',
    },
    {
      ID: 76,
      nomFr: 'Guyana',
      nationaliteFr: 'Guyanienne',
      nomEn: 'Guyana',
      nationaliteEn: 'Guyanese',
      alpha2Code: 'GY',
      alpha3Code: 'GUY',
      dialCode: '592',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 77,
      nomFr: 'Haïti',
      nationaliteFr: 'Haïtienne',
      nomEn: 'Haiti',
      nationaliteEn: 'Haitian',
      alpha2Code: 'HT',
      alpha3Code: 'HTI',
      dialCode: '509',
      prep: 'en',
      phoneFormat: '99-99-9999',
    },
    {
      ID: 78,
      nomFr: 'Honduras',
      nationaliteFr: 'Hondurienne',
      nomEn: 'Honduras',
      nationaliteEn: 'Honduran',
      alpha2Code: 'HN',
      alpha3Code: 'HND',
      dialCode: '504',
      prep: 'au',
      phoneFormat: '9999-99999',
    },
    {
      ID: 79,
      nomFr: 'Hongrie',
      nationaliteFr: 'Hongroise',
      nomEn: 'Hungary',
      nationaliteEn: 'Hungarian',
      alpha2Code: 'HU',
      alpha3Code: 'HUN',
      dialCode: '36',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 80,
      nomFr: 'Inde',
      nationaliteFr: 'Indienne',
      nomEn: 'India',
      nationaliteEn: 'Indian',
      alpha2Code: 'IN',
      alpha3Code: 'IND',
      dialCode: '91',
      prep: 'en',
      phoneFormat: '99999-99999',
    },
    {
      ID: 81,
      nomFr: 'Indonésie',
      nationaliteFr: 'Indonésienne',
      nomEn: 'Indonesia',
      nationaliteEn: 'Indonesian',
      alpha2Code: 'ID',
      alpha3Code: 'IDN',
      dialCode: '62',
      prep: 'en',
      phoneFormat: '999-9999-9999',
    },
    {
      ID: 82,
      nomFr: 'Irak',
      nationaliteFr: 'Irakienne',
      nomEn: 'Iraq',
      nationaliteEn: 'Iraqi',
      alpha2Code: 'IQ',
      alpha3Code: 'IRQ',
      dialCode: '964',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 83,
      nomFr: 'Iran',
      nationaliteFr: 'Iranienne',
      nomEn: 'Iran',
      nationaliteEn: 'Iranian',
      alpha2Code: 'IR',
      alpha3Code: 'IRN',
      dialCode: '98',
      prep: 'en',
      phoneFormat: '999-999-9999',
    },
    {
      ID: 84,
      nomFr: 'Irlande',
      nationaliteFr: 'Irlandaise',
      nomEn: 'Ireland',
      nationaliteEn: 'Irish',
      alpha2Code: 'IE',
      alpha3Code: 'IRL',
      dialCode: '353',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 85,
      nomFr: 'Islande',
      nationaliteFr: 'Islandaise',
      nomEn: 'Iceland',
      nationaliteEn: 'Icelander',
      alpha2Code: 'IS',
      alpha3Code: 'ISL',
      dialCode: '354',
      prep: 'en',
      phoneFormat: '999-9999',
    },
    {
      ID: 86,
      nomFr: 'Israël',
      nationaliteFr: 'Israélienne',
      nomEn: 'Israel',
      nationaliteEn: 'Israeli',
      alpha2Code: 'IL',
      alpha3Code: 'ISR',
      dialCode: '972',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 87,
      nomFr: 'Italie',
      nationaliteFr: 'Italienne',
      nomEn: 'Italy',
      nationaliteEn: 'Italian',
      alpha2Code: 'IT',
      alpha3Code: 'ITA',
      dialCode: '39',
      prep: 'en',
      phoneFormat: '999-999-9999',
    },
    {
      ID: 88,
      nomFr: 'Jamaïque',
      nationaliteFr: 'Jamaïcaine',
      nomEn: 'Jamaica',
      nationaliteEn: 'Jamaican',
      alpha2Code: 'JM',
      alpha3Code: 'JAM',
      dialCode: '1876',
      prep: 'en',
      phoneFormat: '999-9999',
    },
    {
      ID: 89,
      nomFr: 'Japon',
      nationaliteFr: 'Japonaise',
      nomEn: 'Japan',
      nationaliteEn: 'Japanese',
      alpha2Code: 'JP',
      alpha3Code: 'JPN',
      dialCode: '81',
      prep: 'au',
      phoneFormat: '99-9999-9999',
    },
    {
      ID: 90,
      nomFr: 'Jordanie',
      nationaliteFr: 'Jordanienne',
      nomEn: 'Jordan',
      nationaliteEn: 'Jordanian',
      alpha2Code: 'JO',
      alpha3Code: 'JOR',
      dialCode: '962',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 91,
      nomFr: 'Kazakhstan',
      nationaliteFr: 'Kazakhe',
      nomEn: 'Kazakhstan',
      nationaliteEn: 'Kazakh',
      alpha2Code: 'KZ',
      alpha3Code: 'KAZ',
      dialCode: '7',
      prep: 'au',
      phoneFormat: '999-999-9999',
    },
    {
      ID: 92,
      nomFr: 'Kenya',
      nationaliteFr: 'Kényane',
      nomEn: 'Kenya',
      nationaliteEn: 'Kenyan',
      alpha2Code: 'KE',
      alpha3Code: 'KEN',
      dialCode: '254',
      prep: 'au',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 93,
      nomFr: 'Kirghizistan',
      nationaliteFr: 'Kirghize',
      nomEn: 'Kyrgyzstan',
      nationaliteEn: 'Kyrgyz',
      alpha2Code: 'KG',
      alpha3Code: 'KGZ',
      dialCode: '996',
      prep: 'au',
      phoneFormat: '999-999-999',
    },
    {
      ID: 94,
      nomFr: 'Kiribati',
      nationaliteFr: 'Kiribatienne',
      nomEn: 'Kiribati',
      nationaliteEn: 'I-Kiribati',
      alpha2Code: 'KI',
      alpha3Code: 'KIR',
      dialCode: '686',
      prep: 'à',
      phoneFormat: '999-9999',
    },
    {
      ID: 95,
      nomFr: 'Kosovo',
      nationaliteFr: 'Kosovare',
      nomEn: 'Kosovo',
      nationaliteEn: 'Kosovar',
      alpha2Code: 'XK',
      alpha3Code: 'XKX',
      dialCode: '383',
      prep: 'au',
      phoneFormat: '99-999-999',
    },
    {
      ID: 96,
      nomFr: 'Koweït',
      nationaliteFr: 'Koweïtienne',
      nomEn: 'Kuwait',
      nationaliteEn: 'Kuwaiti',
      alpha2Code: 'KW',
      alpha3Code: 'KWT',
      dialCode: '965',
      prep: 'au',
      phoneFormat: '9999-9999',
    },
    {
      ID: 97,
      nomFr: 'Laos',
      nationaliteFr: 'Laotienne',
      nomEn: 'Laos',
      nationaliteEn: 'Laotian',
      alpha2Code: 'LA',
      alpha3Code: 'LAO',
      dialCode: '856',
      prep: 'au',
      phoneFormat: '99-999-999',
    },
    {
      ID: 98,
      nomFr: 'Lesotho',
      nationaliteFr: 'Lésothienne',
      nomEn: 'Lesotho',
      nationaliteEn: 'Basotho',
      alpha2Code: 'LS',
      alpha3Code: 'LSO',
      dialCode: '266',
      prep: 'au',
      phoneFormat: '9999-9999',
    },
    {
      ID: 99,
      nomFr: 'Lettonie',
      nationaliteFr: 'Lettonne',
      nomEn: 'Latvia',
      nationaliteEn: 'Latvian',
      alpha2Code: 'LV',
      alpha3Code: 'LVA',
      dialCode: '371',
      prep: 'en',
      phoneFormat: '999-9999',
    },
    {
      ID: 100,
      nomFr: 'Liban',
      nationaliteFr: 'Libanaise',
      nomEn: 'Lebanon',
      nationaliteEn: 'Lebanese',
      alpha2Code: 'LB',
      alpha3Code: 'LBN',
      dialCode: '961',
      prep: 'au',
      phoneFormat: '99-999-999',
    },
    {
      ID: 101,
      nomFr: 'Liberia',
      nationaliteFr: 'Libérienne',
      nomEn: 'Liberia',
      nationaliteEn: 'Liberian',
      alpha2Code: 'LR',
      alpha3Code: 'LBR',
      dialCode: '231',
      prep: 'au',
      phoneFormat: '99-999-999',
    },
    {
      ID: 102,
      nomFr: 'Libye',
      nationaliteFr: 'Libyenne',
      nomEn: 'Libya',
      nationaliteEn: 'Libyan',
      alpha2Code: 'LY',
      alpha3Code: 'LBY',
      dialCode: '218',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 103,
      nomFr: 'Liechtenstein',
      nationaliteFr: 'Liechtensteinoise',
      nomEn: 'Liechtenstein',
      nationaliteEn: 'Liechtensteiner',
      alpha2Code: 'LI',
      alpha3Code: 'LIE',
      dialCode: '423',
      prep: 'au',
      phoneFormat: '9999-9999',
    },
    {
      ID: 104,
      nomFr: 'Lituanie',
      nationaliteFr: 'Lituanienne',
      nomEn: 'Lithuania',
      nationaliteEn: 'Lithuanian',
      alpha2Code: 'LT',
      alpha3Code: 'LTU',
      dialCode: '370',
      prep: 'en',
      phoneFormat: '999-99999',
    },
    {
      ID: 105,
      nomFr: 'Luxembourg',
      nationaliteFr: 'Luxembourgeoise',
      nomEn: 'Luxembourg',
      nationaliteEn: 'Luxembourger',
      alpha2Code: 'LU',
      alpha3Code: 'LUX',
      dialCode: '352',
      prep: 'au',
      phoneFormat: '999-999-999',
    },
    {
      ID: 106,
      nomFr: 'Macédoine',
      nationaliteFr: 'Macédonienne',
      nomEn: 'North Macedonia',
      nationaliteEn: 'Macedonian',
      alpha2Code: 'MK',
      alpha3Code: 'MKD',
      dialCode: '389',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 107,
      nomFr: 'Madagascar',
      nationaliteFr: 'Malgache',
      nomEn: 'Madagascar',
      nationaliteEn: 'Malagasy',
      alpha2Code: 'MG',
      alpha3Code: 'MDG',
      dialCode: '261',
      prep: 'à',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 108,
      nomFr: 'Malaisie',
      nationaliteFr: 'Malaisienne',
      nomEn: 'Malaysia',
      nationaliteEn: 'Malaysian',
      alpha2Code: 'MY',
      alpha3Code: 'MYS',
      dialCode: '60',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 109,
      nomFr: 'Malawi',
      nationaliteFr: 'Malawienne',
      nomEn: 'Malawi',
      nationaliteEn: 'Malawian',
      alpha2Code: 'MW',
      alpha3Code: 'MWI',
      dialCode: '265',
      prep: 'au',
      phoneFormat: '9999-9999',
    },
    {
      ID: 110,
      nomFr: 'Maldives',
      nationaliteFr: 'Maldivienne',
      nomEn: 'Maldives',
      nationaliteEn: 'Maldivian',
      alpha2Code: 'MV',
      alpha3Code: 'MDV',
      dialCode: '960',
      prep: 'aux',
      phoneFormat: '999-9999',
    },
    {
      ID: 111,
      nomFr: 'Mali',
      nationaliteFr: 'Malienne',
      nomEn: 'Mali',
      nationaliteEn: 'Malian',
      alpha2Code: 'ML',
      alpha3Code: 'MLI',
      dialCode: '223',
      prep: 'au',
      phoneFormat: '99-99-9999',
    },
    {
      ID: 112,
      nomFr: 'Malte',
      nationaliteFr: 'Maltaise',
      nomEn: 'Malta',
      nationaliteEn: 'Maltese',
      alpha2Code: 'MT',
      alpha3Code: 'MLT',
      dialCode: '356',
      prep: 'à',
      phoneFormat: '9999-9999',
    },
    {
      ID: 113,
      nomFr: 'Maroc',
      nationaliteFr: 'Marocaine',
      nomEn: 'Morocco',
      nationaliteEn: 'Moroccan',
      alpha2Code: 'MA',
      alpha3Code: 'MAR',
      dialCode: '212',
      prep: 'au',
      phoneFormat: '99-9999-999',
    },
    {
      ID: 114,
      nomFr: 'Marshall',
      nationaliteFr: 'Marshallaise',
      nomEn: 'Marshall Islands',
      nationaliteEn: 'Marshallese',
      alpha2Code: 'MH',
      alpha3Code: 'MHL',
      dialCode: '692',
      prep: 'aux',
      phoneFormat: '999-9999',
    },
    {
      ID: 115,
      nomFr: 'Maurice (Île)',
      nationaliteFr: 'Mauricienne',
      nomEn: 'Mauritius',
      nationaliteEn: 'Mauritian',
      alpha2Code: 'MU',
      alpha3Code: 'MUS',
      dialCode: '230',
      prep: 'à',
      phoneFormat: '9999-9999',
    },
    {
      ID: 116,
      nomFr: 'Mauritanie',
      nationaliteFr: 'Mauritanienne',
      nomEn: 'Mauritania',
      nationaliteEn: 'Mauritanian',
      alpha2Code: 'MR',
      alpha3Code: 'MRT',
      dialCode: '222',
      prep: 'en',
      phoneFormat: '99-99-9999',
    },
    {
      ID: 117,
      nomFr: 'Mexique',
      nationaliteFr: 'Mexicaine',
      nomEn: 'Mexico',
      nationaliteEn: 'Mexican',
      alpha2Code: 'MX',
      alpha3Code: 'MEX',
      dialCode: '52',
      prep: 'au',
      phoneFormat: '99-9999-9999',
    },
    {
      ID: 118,
      nomFr: 'Micronésie, Fédération des États de',
      nationaliteFr: 'Micronésienne',
      nomEn: 'Micronesia',
      nationaliteEn: 'Micronesian',
      alpha2Code: 'FM',
      alpha3Code: 'FSM',
      dialCode: '691',
      prep: 'en',
      phoneFormat: '999-9999',
    },
    {
      ID: 119,
      nomFr: 'Moldavie',
      nationaliteFr: 'Moldave',
      nomEn: 'Moldova',
      nationaliteEn: 'Moldovan',
      alpha2Code: 'MD',
      alpha3Code: 'MDA',
      dialCode: '373',
      prep: 'en',
      phoneFormat: '9999-9999',
    },
    {
      ID: 120,
      nomFr: 'Monaco',
      nationaliteFr: 'Monégasque',
      nomEn: 'Monaco',
      nationaliteEn: 'Monegasque',
      alpha2Code: 'MC',
      alpha3Code: 'MCO',
      dialCode: '377',
      prep: 'à',
      phoneFormat: '9999-9999',
    },
    {
      ID: 121,
      nomFr: 'Mongolie',
      nationaliteFr: 'Mongole',
      nomEn: 'Mongolia',
      nationaliteEn: 'Mongolian',
      alpha2Code: 'MN',
      alpha3Code: 'MNG',
      dialCode: '976',
      prep: 'en',
      phoneFormat: '99-99-9999',
    },
    {
      ID: 122,
      nomFr: 'Monténégro',
      nationaliteFr: 'Monténégrine',
      nomEn: 'Montenegro',
      nationaliteEn: 'Montenegrin',
      alpha2Code: 'ME',
      alpha3Code: 'MNE',
      dialCode: '382',
      prep: 'au',
      phoneFormat: '99-999-999',
    },
    {
      ID: 123,
      nomFr: 'Mozambique',
      nationaliteFr: 'Mozambicaine',
      nomEn: 'Mozambique',
      nationaliteEn: 'Mozambican',
      alpha2Code: 'MZ',
      alpha3Code: 'MOZ',
      dialCode: '258',
      prep: 'au',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 124,
      nomFr: 'Namibie',
      nationaliteFr: 'Namibienne',
      nomEn: 'Namibia',
      nationaliteEn: 'Namibian',
      alpha2Code: 'NA',
      alpha3Code: 'NAM',
      dialCode: '264',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 125,
      nomFr: 'Nauru',
      nationaliteFr: 'Nauruane',
      nomEn: 'Nauru',
      nationaliteEn: 'Nauruan',
      alpha2Code: 'NR',
      alpha3Code: 'NRU',
      dialCode: '674',
      prep: 'à',
      phoneFormat: '999-9999',
    },
    {
      ID: 126,
      nomFr: 'Népal',
      nationaliteFr: 'Népalaise',
      nomEn: 'Nepal',
      nationaliteEn: 'Nepalese',
      alpha2Code: 'NP',
      alpha3Code: 'NPL',
      dialCode: '977',
      prep: 'au',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 127,
      nomFr: 'Nicaragua',
      nationaliteFr: 'Nicaraguayenne',
      nomEn: 'Nicaragua',
      nationaliteEn: 'Nicaraguan',
      alpha2Code: 'NI',
      alpha3Code: 'NIC',
      dialCode: '505',
      prep: 'au',
      phoneFormat: '9999-9999',
    },
    {
      ID: 128,
      nomFr: 'Niger',
      nationaliteFr: 'Nigérienne',
      nomEn: 'Niger',
      nationaliteEn: 'Nigerien',
      alpha2Code: 'NE',
      alpha3Code: 'NER',
      dialCode: '227',
      prep: 'au',
      phoneFormat: '99-99-9999',
    },
    {
      ID: 129,
      nomFr: 'Nigeria',
      nationaliteFr: 'Nigériane',
      nomEn: 'Nigeria',
      nationaliteEn: 'Nigerian',
      alpha2Code: 'NG',
      alpha3Code: 'NGA',
      dialCode: '234',
      prep: 'au',
      phoneFormat: '999-999-9999',
    },
    {
      ID: 130,
      nomFr: 'Norvège',
      nationaliteFr: 'Norvégienne',
      nomEn: 'Norway',
      nationaliteEn: 'Norwegian',
      alpha2Code: 'NO',
      alpha3Code: 'NOR',
      dialCode: '47',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 131,
      nomFr: 'Nouvelle-Zélande',
      nationaliteFr: 'Néo-Zélandaise',
      nomEn: 'New Zealand',
      nationaliteEn: 'New Zealander',
      alpha2Code: 'NZ',
      alpha3Code: 'NZL',
      dialCode: '64',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 132,
      nomFr: 'Oman',
      nationaliteFr: 'Omanaise',
      nomEn: 'Oman',
      nationaliteEn: 'Omani',
      alpha2Code: 'OM',
      alpha3Code: 'OMN',
      dialCode: '968',
      prep: 'à',
      phoneFormat: '99-999-999',
    },
    {
      ID: 133,
      nomFr: 'Ouganda',
      nationaliteFr: 'Ougandaise',
      nomEn: 'Uganda',
      nationaliteEn: 'Ugandan',
      alpha2Code: 'UG',
      alpha3Code: 'UGA',
      dialCode: '256',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 134,
      nomFr: 'Ouzbékistan',
      nationaliteFr: 'Ouzbèke',
      nomEn: 'Uzbekistan',
      nationaliteEn: 'Uzbek',
      alpha2Code: 'UZ',
      alpha3Code: 'UZB',
      dialCode: '998',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 135,
      nomFr: 'Pakistan',
      nationaliteFr: 'Pakistanaise',
      nomEn: 'Pakistan',
      nationaliteEn: 'Pakistani',
      alpha2Code: 'PK',
      alpha3Code: 'PAK',
      dialCode: '92',
      prep: 'au',
      phoneFormat: '999-999-9999',
    },
    {
      ID: 136,
      nomFr: 'Panama',
      nationaliteFr: 'Panaméenne',
      nomEn: 'Panama',
      nationaliteEn: 'Panamanian',
      alpha2Code: 'PA',
      alpha3Code: 'PAN',
      dialCode: '507',
      prep: 'au',
      phoneFormat: '999-9999',
    },
    {
      ID: 137,
      nomFr: 'Papouasie-Nouvelle-Guinée',
      nationaliteFr: 'Papouasienne',
      nomEn: 'Papua New Guinea',
      nationaliteEn: 'Papua New Guinean',
      alpha2Code: 'PG',
      alpha3Code: 'PNG',
      dialCode: '675',
      prep: 'en',
      phoneFormat: '999-9999',
    },
    {
      ID: 138,
      nomFr: 'Paraguay',
      nationaliteFr: 'Paraguayenne',
      nomEn: 'Paraguay',
      nationaliteEn: 'Paraguayan',
      alpha2Code: 'PY',
      alpha3Code: 'PRY',
      dialCode: '595',
      prep: 'au',
      phoneFormat: '999-999-999',
    },
    {
      ID: 139,
      nomFr: 'Pays-Bas',
      nationaliteFr: 'Néerlandaise',
      nomEn: 'Netherlands',
      nationaliteEn: 'Dutch',
      alpha2Code: 'NL',
      alpha3Code: 'NLD',
      dialCode: '31',
      prep: 'aux',
      phoneFormat: '999-999-999',
    },
    {
      ID: 140,
      nomFr: 'Pérou',
      nationaliteFr: 'Péruvienne',
      nomEn: 'Peru',
      nationaliteEn: 'Peruvian',
      alpha2Code: 'PE',
      alpha3Code: 'PER',
      dialCode: '51',
      prep: 'au',
      phoneFormat: '999-999-999',
    },
    {
      ID: 141,
      nomFr: 'Philippines',
      nationaliteFr: 'Philippine',
      nomEn: 'Philippines',
      nationaliteEn: 'Filipino',
      alpha2Code: 'PH',
      alpha3Code: 'PHL',
      dialCode: '63',
      prep: 'aux',
      phoneFormat: '999-999-9999',
    },
    {
      ID: 142,
      nomFr: 'Pologne',
      nationaliteFr: 'Polonaise',
      nomEn: 'Poland',
      nationaliteEn: 'Polish',
      alpha2Code: 'PL',
      alpha3Code: 'POL',
      dialCode: '48',
      prep: 'en',
      phoneFormat: '999-999-999',
    },
    {
      ID: 143,
      nomFr: 'Portugal',
      nationaliteFr: 'Portugaise',
      nomEn: 'Portugal',
      nationaliteEn: 'Portuguese',
      alpha2Code: 'PT',
      alpha3Code: 'PRT',
      dialCode: '351',
      prep: 'au',
      phoneFormat: '999-999-999',
    },
    {
      ID: 144,
      nomFr: 'Qatar',
      nationaliteFr: 'Qatari',
      nomEn: 'Qatar',
      nationaliteEn: 'Qatari',
      alpha2Code: 'QA',
      alpha3Code: 'QAT',
      dialCode: '974',
      prep: 'au',
      phoneFormat: '9999-9999',
    },
    {
      ID: 145,
      nomFr: 'République dominicaine',
      nationaliteFr: 'Dominicaine',
      nomEn: 'Dominican Republic',
      nationaliteEn: 'Dominican',
      alpha2Code: 'DO',
      alpha3Code: 'DOM',
      dialCode: '1809',
      prep: 'en',
      phoneFormat: '999-9999',
    },
    {
      ID: 146,
      nomFr: 'République tchèque',
      nationaliteFr: 'Tchèque',
      nomEn: 'Czech Republic',
      nationaliteEn: 'Czech',
      alpha2Code: 'CZ',
      alpha3Code: 'CZE',
      dialCode: '420',
      prep: 'en',
      phoneFormat: '999-999-999',
    },
    {
      ID: 147,
      nomFr: 'Roumanie',
      nationaliteFr: 'Roumaine',
      nomEn: 'Romania',
      nationaliteEn: 'Romanian',
      alpha2Code: 'RO',
      alpha3Code: 'ROU',
      dialCode: '40',
      prep: 'en',
      phoneFormat: '9999-999-999',
    },
    {
      ID: 148,
      nomFr: 'Royaume-Uni',
      nationaliteFr: 'Britannique',
      nomEn: 'United Kingdom',
      nationaliteEn: 'British',
      alpha2Code: 'GB',
      alpha3Code: 'GBR',
      dialCode: '44',
      prep: 'au',
      phoneFormat: '9999-999999',
    },
    {
      ID: 149,
      nomFr: 'Russie',
      nationaliteFr: 'Russe',
      nomEn: 'Russia',
      nationaliteEn: 'Russian',
      alpha2Code: 'RU',
      alpha3Code: 'RUS',
      dialCode: '7',
      prep: 'en',
      phoneFormat: '999-999-9999',
    },
    {
      ID: 150,
      nomFr: 'Rwanda',
      nationaliteFr: 'Rwandaise',
      nomEn: 'Rwanda',
      nationaliteEn: 'Rwandan',
      alpha2Code: 'RW',
      alpha3Code: 'RWA',
      dialCode: '250',
      prep: 'au',
      phoneFormat: '999-999-999',
    },
    {
      ID: 151,
      nomFr: 'Saint-Christophe-et-Niévès',
      nationaliteFr: 'Christophienne',
      nomEn: 'Saint Kitts and Nevis',
      nationaliteEn: 'Kittitian',
      alpha2Code: 'KN',
      alpha3Code: 'KNA',
      dialCode: '1869',
      prep: 'à',
      phoneFormat: '999-9999',
    },
    {
      ID: 152,
      nomFr: 'Sainte-Lucie',
      nationaliteFr: 'Lucienne',
      nomEn: 'Saint Lucia',
      nationaliteEn: 'Saint Lucian',
      alpha2Code: 'LC',
      alpha3Code: 'LCA',
      dialCode: '1758',
      prep: 'à',
      phoneFormat: '999-9999',
    },
    {
      ID: 153,
      nomFr: 'Saint-Marin',
      nationaliteFr: 'Saint-Marinaise',
      nomEn: 'San Marino',
      nationaliteEn: 'Sammarinese',
      alpha2Code: 'SM',
      alpha3Code: 'SMR',
      dialCode: '378',
      prep: 'à',
      phoneFormat: '999-999999',
    },
    {
      ID: 154,
      nomFr: 'Saint-Vincent-et-les-Grenadines',
      nationaliteFr: 'Vincentaise',
      nomEn: 'Saint Vincent and the Grenadines',
      nationaliteEn: 'Vincentian',
      alpha2Code: 'VC',
      alpha3Code: 'VCT',
      dialCode: '1784',
      prep: 'à',
      phoneFormat: '999-9999',
    },
    {
      ID: 155,
      nomFr: 'Salomon (Îles)',
      nationaliteFr: 'Salomonaise',
      nomEn: 'Solomon Islands',
      nationaliteEn: 'Solomon Islander',
      alpha2Code: 'SB',
      alpha3Code: 'SLB',
      dialCode: '677',
      prep: 'aux',
      phoneFormat: '999-9999',
    },
    {
      ID: 156,
      nomFr: 'São-Tomé-et-Príncipe',
      nationaliteFr: 'Santoméenne',
      nomEn: 'São Tomé and Príncipe',
      nationaliteEn: 'Santomean',
      alpha2Code: 'ST',
      alpha3Code: 'STP',
      dialCode: '239',
      prep: 'à',
      phoneFormat: '999-9999',
    },
    {
      ID: 157,
      nomFr: 'Salvador',
      nationaliteFr: 'Salvadorienne',
      nomEn: 'El Salvador',
      nationaliteEn: 'Salvadoran',
      alpha2Code: 'SV',
      alpha3Code: 'SLV',
      dialCode: '503',
      prep: 'au',
      phoneFormat: '9999-9999',
    },
    {
      ID: 158,
      nomFr: 'Samoa occidentales',
      nationaliteFr: 'Samoane',
      nomEn: 'Samoa',
      nationaliteEn: 'Samoan',
      alpha2Code: 'WS',
      alpha3Code: 'WSM',
      dialCode: '685',
      prep: 'aux',
      phoneFormat: '99999',
    },
    {
      ID: 159,
      nomFr: 'Sénégal',
      nationaliteFr: 'Sénégalais(e)',
      nomEn: 'Senegal',
      nationaliteEn: 'Senegalese',
      alpha2Code: 'SN',
      alpha3Code: 'SEN',
      dialCode: '221',
      prep: 'au',
      phoneFormat: '99-999-99-99',
    },
    {
      ID: 160,
      nomFr: 'Serbie',
      nationaliteFr: 'Serbe',
      nomEn: 'Serbia',
      nationaliteEn: 'Serbian',
      alpha2Code: 'RS',
      alpha3Code: 'SRB',
      dialCode: '381',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 161,
      nomFr: 'Seychelles',
      nationaliteFr: 'Seychelloise',
      nomEn: 'Seychelles',
      nationaliteEn: 'Seychellois',
      alpha2Code: 'SC',
      alpha3Code: 'SYC',
      dialCode: '248',
      prep: 'aux',
      phoneFormat: '999-9999',
    },
    {
      ID: 162,
      nomFr: 'Sierra Leone',
      nationaliteFr: 'Sierra-Léonaise',
      nomEn: 'Sierra Leone',
      nationaliteEn: 'Sierra Leonean',
      alpha2Code: 'SL',
      alpha3Code: 'SLE',
      dialCode: '232',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 163,
      nomFr: 'Singapour',
      nationaliteFr: 'Singapourien(ne)',
      nomEn: 'Singapore',
      nationaliteEn: 'Singaporean',
      alpha2Code: 'SG',
      alpha3Code: 'SGP',
      dialCode: '65',
      prep: 'à',
      phoneFormat: '9999-9999',
    },
    {
      ID: 164,
      nomFr: 'Slovaquie',
      nationaliteFr: 'Slovaque',
      nomEn: 'Slovakia',
      nationaliteEn: 'Slovak',
      alpha2Code: 'SK',
      alpha3Code: 'SVK',
      dialCode: '421',
      prep: 'en',
      phoneFormat: '999-999-999',
    },
    {
      ID: 165,
      nomFr: 'Slovénie',
      nationaliteFr: 'Slovène',
      nomEn: 'Slovenia',
      nationaliteEn: 'Slovenian',
      alpha2Code: 'SI',
      alpha3Code: 'SVN',
      dialCode: '386',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 166,
      nomFr: 'Somalie',
      nationaliteFr: 'Somalienne',
      nomEn: 'Somalia',
      nationaliteEn: 'Somali',
      alpha2Code: 'SO',
      alpha3Code: 'SOM',
      dialCode: '252',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 167,
      nomFr: 'Soudan',
      nationaliteFr: 'Soudanaise',
      nomEn: 'Sudan',
      nationaliteEn: 'Sudanese',
      alpha2Code: 'SD',
      alpha3Code: 'SDN',
      dialCode: '249',
      prep: 'au',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 168,
      nomFr: 'Soudan du Sud',
      nationaliteFr: 'Sud-Soudanaise',
      nomEn: 'South Sudan',
      nationaliteEn: 'South Sudanese',
      alpha2Code: 'SS',
      alpha3Code: 'SSD',
      dialCode: '211',
      prep: 'au',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 169,
      nomFr: 'Sri Lanka',
      nationaliteFr: 'Sri-Lankaise',
      nomEn: 'Sri Lanka',
      nationaliteEn: 'Sri Lankan',
      alpha2Code: 'LK',
      alpha3Code: 'LKA',
      dialCode: '94',
      prep: 'au',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 170,
      nomFr: 'Suède',
      nationaliteFr: 'Suédoise',
      nomEn: 'Sweden',
      nationaliteEn: 'Swedish',
      alpha2Code: 'SE',
      alpha3Code: 'SWE',
      dialCode: '46',
      prep: 'en',
      phoneFormat: '999-999-999',
    },
    {
      ID: 171,
      nomFr: 'Suisse',
      nationaliteFr: 'Suisse',
      nomEn: 'Switzerland',
      nationaliteEn: 'Swiss',
      alpha2Code: 'CH',
      alpha3Code: 'CHE',
      dialCode: '41',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 172,
      nomFr: 'Surinam',
      nationaliteFr: 'Surinamaise',
      nomEn: 'Suriname',
      nationaliteEn: 'Surinamese',
      alpha2Code: 'SR',
      alpha3Code: 'SUR',
      dialCode: '597',
      prep: 'au',
      phoneFormat: '999-9999',
    },
    {
      ID: 173,
      nomFr: 'Swaziland',
      nationaliteFr: 'Swazie',
      nomEn: 'Eswatini (Swaziland)',
      nationaliteEn: 'Swazi',
      alpha2Code: 'SZ',
      alpha3Code: 'SWZ',
      dialCode: '268',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 174,
      nomFr: 'Syrie',
      nationaliteFr: 'Syrienne',
      nomEn: 'Syria',
      nationaliteEn: 'Syrian',
      alpha2Code: 'SY',
      alpha3Code: 'SYR',
      dialCode: '963',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 175,
      nomFr: 'Tadjikistan',
      nationaliteFr: 'Tadjike',
      nomEn: 'Tajikistan',
      nationaliteEn: 'Tajik',
      alpha2Code: 'TJ',
      alpha3Code: 'TJK',
      dialCode: '992',
      prep: 'au',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 176,
      nomFr: 'Tanzanie',
      nationaliteFr: 'Tanzanienne',
      nomEn: 'Tanzania',
      nationaliteEn: 'Tanzanian',
      alpha2Code: 'TZ',
      alpha3Code: 'TZA',
      dialCode: '255',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 177,
      nomFr: 'Tchad',
      nationaliteFr: 'Tchadienne',
      nomEn: 'Chad',
      nationaliteEn: 'Chadian',
      alpha2Code: 'TD',
      alpha3Code: 'TCD',
      dialCode: '235',
      prep: 'au',
      phoneFormat: '99-99-99-99',
    },
    {
      ID: 178,
      nomFr: 'Timor oriental',
      nationaliteFr: 'Timoraise',
      nomEn: 'Timor-Leste',
      nationaliteEn: 'Timorese',
      alpha2Code: 'TL',
      alpha3Code: 'TLS',
      dialCode: '670',
      prep: 'au',
      phoneFormat: '999-9999',
    },
    {
      ID: 179,
      nomFr: 'Thaïlande',
      nationaliteFr: 'Thaïlandaise',
      nomEn: 'Thailand',
      nationaliteEn: 'Thai',
      alpha2Code: 'TH',
      alpha3Code: 'THA',
      dialCode: '66',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 180,
      nomFr: 'Togo',
      nationaliteFr: 'Togolais(e)',
      nomEn: 'Togo',
      nationaliteEn: 'Togolese',
      alpha2Code: 'TG',
      alpha3Code: 'TGO',
      dialCode: '228',
      prep: 'au',
      phoneFormat: '99-99-99-99',
    },
    {
      ID: 181,
      nomFr: 'Tonga',
      nationaliteFr: 'Tongienne',
      nomEn: 'Tonga',
      nationaliteEn: 'Tongan',
      alpha2Code: 'TO',
      alpha3Code: 'TON',
      dialCode: '676',
      prep: 'à',
      phoneFormat: '99999',
    },
    {
      ID: 182,
      nomFr: 'Trinité-et-Tobago',
      nationaliteFr: 'Trinidadienne',
      nomEn: 'Trinidad and Tobago',
      nationaliteEn: 'Trinidadian',
      alpha2Code: 'TT',
      alpha3Code: 'TTO',
      dialCode: '1868',
      prep: 'à la',
      phoneFormat: '999-9999',
    },
    {
      ID: 183,
      nomFr: 'Tunisie',
      nationaliteFr: 'Tunisienne',
      nomEn: 'Tunisia',
      nationaliteEn: 'Tunisian',
      alpha2Code: 'TN',
      alpha3Code: 'TUN',
      dialCode: '216',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 184,
      nomFr: 'Turkménistan',
      nationaliteFr: 'Turkmène',
      nomEn: 'Turkmenistan',
      nationaliteEn: 'Turkmen',
      alpha2Code: 'TM',
      alpha3Code: 'TKM',
      dialCode: '993',
      prep: 'au',
      phoneFormat: '99-99-99-99',
    },
    {
      ID: 185,
      nomFr: 'Turquie',
      nationaliteFr: 'Turcque',
      nomEn: 'Turkey',
      nationaliteEn: 'Turkish',
      alpha2Code: 'TR',
      alpha3Code: 'TUR',
      dialCode: '90',
      prep: 'en',
      phoneFormat: '999-999-9999',
    },
    {
      ID: 186,
      nomFr: 'Tuvalu',
      nationaliteFr: 'Tuvaluane',
      nomEn: 'Tuvalu',
      nationaliteEn: 'Tuvaluan',
      alpha2Code: 'TV',
      alpha3Code: 'TUV',
      dialCode: '688',
      prep: 'à',
      phoneFormat: '999-999',
    },
    {
      ID: 187,
      nomFr: 'Ukraine',
      nationaliteFr: 'Ukrainien(ne)',
      nomEn: 'Ukraine',
      nationaliteEn: 'Ukrainian',
      alpha2Code: 'UA',
      alpha3Code: 'UKR',
      dialCode: '380',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 188,
      nomFr: 'Uruguay',
      nationaliteFr: 'Uruguayen(ne)',
      nomEn: 'Uruguay',
      nationaliteEn: 'Uruguayan',
      alpha2Code: 'UY',
      alpha3Code: 'URY',
      dialCode: '598',
      prep: 'en',
      phoneFormat: '99-999-999',
    },
    {
      ID: 189,
      nomFr: 'Vanuatu',
      nationaliteFr: 'Vanuatuan(e)',
      nomEn: 'Vanuatu',
      nationaliteEn: 'Ni-Vanuatu',
      alpha2Code: 'VU',
      alpha3Code: 'VUT',
      dialCode: '678',
      prep: 'au',
      phoneFormat: '999-999',
    },
    {
      ID: 190,
      nomFr: 'Vatican',
      nationaliteFr: 'Vatican(e)',
      nomEn: 'Vatican City',
      nationaliteEn: 'Vatican',
      alpha2Code: 'VA',
      alpha3Code: 'VAT',
      dialCode: '379',
      prep: 'au',
      phoneFormat: '999-9999',
    },
    {
      ID: 191,
      nomFr: 'Venezuela',
      nationaliteFr: 'Vénézuélien(ne)',
      nomEn: 'Venezuela',
      nationaliteEn: 'Venezuelan',
      alpha2Code: 'VE',
      alpha3Code: 'VEN',
      dialCode: '58',
      prep: 'au',
      phoneFormat: '99-9999999',
    },
    {
      ID: 192,
      nomFr: 'Vietnam',
      nationaliteFr: 'Vietnamien(ne)',
      nomEn: 'Vietnam',
      nationaliteEn: 'Vietnamese',
      alpha2Code: 'VN',
      alpha3Code: 'VNM',
      dialCode: '84',
      prep: 'au',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 193,
      nomFr: 'Yémen',
      nationaliteFr: 'Yéménite',
      nomEn: 'Yemen',
      nationaliteEn: 'Yemeni',
      alpha2Code: 'YE',
      alpha3Code: 'YEM',
      dialCode: '967',
      prep: 'au',
      phoneFormat: '9-999-999',
    },
    {
      ID: 194,
      nomFr: 'Zambie',
      nationaliteFr: 'Zambien(ne)',
      nomEn: 'Zambia',
      nationaliteEn: 'Zambian',
      alpha2Code: 'ZM',
      alpha3Code: 'ZMB',
      dialCode: '260',
      prep: 'en',
      phoneFormat: '99-999-9999',
    },
    {
      ID: 195,
      nomFr: 'Zimbabwe',
      nationaliteFr: 'Zimbabwéen(ne)',
      nomEn: 'Zimbabwe',
      nationaliteEn: 'Zimbabwean',
      alpha2Code: 'ZW',
      alpha3Code: 'ZWE',
      dialCode: '263',
      prep: 'au',
      phoneFormat: '99-999-999',
    },
  ];